# Generated by Django 2.2.11 on 2020-03-30 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.CharField(max_length=999)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('quantity', models.CharField(max_length=999, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Solo números enteros')])),
            ],
        ),
    ]
